use action for tests
iter8-tools/docs pull request #18
Opened 2022-03-02 16:02 UTC by kalantar

Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

2022-03-03 21:53 UTC, kalantar commented
This is ready for review.

2022-03-03 22:14 UTC, sriumcp requested changes
minor fixes requested

2022-03-03 22:14 UTC, sriumcp commented on .github/workflows/tests.yaml
> +        ip -f inet addr show docker0 | grep -Po 'inet \K[\d.]+'
We can remove this line.

2022-03-03 22:14 UTC, sriumcp commented on .github/workflows/tests.yaml
> +          url: http://127.0.0.1/get
Host information should be set in the same manner as gRPC -- extracting the address from docker bridge seems like the more robust approach

2022-03-03 22:14 UTC, sriumcp commented on .github/workflows/tests.yaml
> +          url: http://127.0.0.1/post
Host information should be set in the same manner as gRPC -- extracting the address from docker bridge seems like the more robust approach

2022-03-03 22:14 UTC, sriumcp commented on .github/workflows/tests.yaml
> +          url: http://127.0.0.1/get
Host information should be set in the same manner as gRPC -- extracting the address from docker bridge seems like the more robust approach

2022-03-04 15:08 UTC, sriumcp approved these changes
lgtm

2022-03-04 15:09 UTC, merged