Add documentation for notify task
iter8-tools/docs pull request #38
Opened 2022-08-26 17:24 UTC by Alan-Cha

2022-08-29 15:39 UTC, kalantar commented on docs/tutorials/integrations/ghactions.md
> +There are two ways that you can use Iter8 with GitHub. You can [run Iter8 CLI within a GitHub Actions workflow](#use-iter8-in-a-github-actions-workflow) and you can also [use Iter8 to trigger a GitHu
nitpick "in the context of an experiment" -> "from an experiment"

2022-08-29 15:41 UTC, sriumcp requested changes

2022-08-29 15:41 UTC, sriumcp commented on docs/user-guide/tasks/slack.md
> +| payloadTemplateURL | string | No | [https://raw.githubusercontent.com/iter8-tools/hub/main/templates/_payload-slack.tpl](https://raw.githubusercontent.com/iter8-tools/hub/main/templates/_payload-sl
The default value of the URL needs fixing.

2022-08-30 14:35 UTC, sriumcp approved these changes
lgtm

2022-08-30 14:36 UTC, merged