Make istio-prom more flexible
iter8-tools/docs pull request #43
Opened 2022-10-21 22:19 UTC by Alan-Cha

2022-10-24 15:13 UTC, kalantar requested changes

2022-10-24 15:13 UTC, kalantar commented on docs/user-guide/tasks/custommetrics.md
> +              {{ $key }}="{{ $val }}",
Use a link to this document instead of copying the document into the md file.

2022-10-24 15:13 UTC, kalantar commented on docs/tutorials/custom-metrics/two-or-more-versions.md
> +--set 'custommetrics.versionValues[0].reporter=default' \
- common values shoud use `values`
- add in `labels`

2022-10-24 15:13 UTC, kalantar commented on docs/user-guide/tasks/custommetrics.md
> +    --set 'custommetrics.versionValues[0].reporter=default' \
same comments as above

2022-11-04 12:25 UTC, kalantar requested changes

2022-11-04 12:25 UTC, kalantar commented on docs/tutorials/custom-metrics/two-or-more-versions.md
> +--set custommetrics.templates.istio-prom="https://raw.githubusercontent.com/iter8-tools/hub/main/templates/custommetrics/istio-prom.tpl" \
same question

2022-11-04 12:25 UTC, kalantar commented on docs/user-guide/tasks/custommetrics.md
> +--set custommetrics.templates.istio-prom="https://raw.githubusercontent.com/iter8-tools/hub/main/templates/custommetrics/istio-prom.tpl" \
and here

2022-11-04 12:25 UTC, kalantar commented on docs/user-guide/tasks/custommetrics.md
> +  * [istio-prom](https://github.com/iter8-tools/hub/blob/main/templates/custommetrics/istio-prom.tpl) for [Istio's Prometheus plugin](https://istio.io/latest/docs/ops/integrations/prometheus/)
and here

2022-11-04 12:25 UTC, kalantar commented on docs/user-guide/tasks/custommetrics.md
> +    --set custommetrics.templates.istio-prom="https://raw.githubusercontent.com/iter8-tools/hub/main/templates/custommetrics/istio-prom.tpl" \
and here

2022-11-04 13:11 UTC, sriumcp requested changes
Perhaps this should in draft mode, until we merge and release `iter8` and `hub` PRs, and then get a version specific reference for the templates (i.e., `v0.12.x` references instead of `main` or `master`).

2022-11-04 15:28 UTC, Alan-Cha commented on docs/tutorials/custom-metrics/one-version.md
> +--set custommetrics.templates.istio-prom="https://raw.githubusercontent.com/iter8-tools/hub/main/templates/custommetrics/istio-prom.tpl" \
Yes, I was planning on making another set of PRs to change all these links to be version specific. I cannot do it until a version has been made.

2022-11-04 15:49 UTC, Alan-Cha commented
> Perhaps this should in draft mode, until we merge and release iter8 and hub PRs, and then get a version specific reference for the templates (i.e., v0.12.x references instead of main or master).

@sriumcp @kalantar One issue is that the links in hub are not pointing to the final version either. Because I'm moving files around in hub and hub contains some self-referential links, after making a new release, I will have to make another PR for hub.

Because we have version-specific self-referential links in hub, doesn't that mean they will always be out of date? This might be confusing to users. Currently, I only plan on updating these links every time there is a significant change. There may be a big gap between the link version and the current version over time. I think as a user, I would expect the link to always point at the current version, but this isn't very practical for me to manually update links with every PR.

I think our system current doesn't work well with these links. It seems to me that the best way to handle this is to use a Github workflow that uses the release tag to generate the correct links. However, this seems to be low priority for now.

2022-11-04 15:57 UTC, sriumcp commented
> > Perhaps this should in draft mode, until we merge and release iter8 and hub PRs, and then get a version specific reference for the templates (i.e., v0.12.x references instead of main or master).
> 
> @sriumcp @kalantar One issue is that the links in hub are not pointing to the final version either. Because I'm moving files around in hub and hub contains some self-referential links, after making a new release, I will have to make another PR for hub.
> 
> Because we have version-specific self-referential links in hub, doesn't that mean they will always be out of date? This might be confusing to users. Currently, I only plan on updating these links every time there is a significant change. There may be a big gap between the link version and the current version over time. I think as a user, I would expect the link to always point at the current version, but this isn't very practical for me to manually update links with every PR.
> 
> I think our system current doesn't work well with these links. It seems to me that the best way to handle this is to use a Github workflow that uses the release tag to generate the correct links. However, this seems to be low priority for now.

Agree with all of the above. There is no need to manually update links on every PR.

However, we want links to be versioned and not pointing to `master` or `main`. So, it is ok if the link says v0.12.8 (when the latest version is in fact v0.12.10 or even v0.13.0 for that matter), as long as things work as promised.

Also, I think we should probably think of docs as declaring a dependency on iter8 and hub. So, a specific version of the docs will have pinned dependencies on iter8 and hub.

2022-11-04 21:03 UTC, sriumcp approved these changes
lgtm.

2022-11-08 16:16 UTC, sriumcp approved these changes
lgtm

2022-11-08 16:17 UTC, merged