Update HTTP and gRPC tutorials
iter8-tools/docs pull request #65
Opened 2023-02-14 07:40 UTC by Alan-Cha

2023-02-14 07:52 UTC, Alan-Cha commented on docs/getting-started/logs.md
> +      time=2022-06-27 15:48:59 level=info msg=task 1: ready: started
This was a change I made previously but I see it was never updated in the docs.

2023-02-14 14:41 UTC, kalantar submitted a review, later dismissed
This looks good. Approving; my comments are nice to have but not necessary.

2023-02-14 16:23 UTC, sriumcp requested changes

2023-02-14 16:23 UTC, sriumcp commented on docs/getting-started/your-first-experiment.md
> +=== "Get example"
GET

2023-02-14 16:23 UTC, sriumcp commented on docs/getting-started/your-first-experiment.md
> +=== "Post example"
POST

2023-02-14 16:23 UTC, sriumcp commented on docs/tutorials/load-test-grpc.md
> +    ??? note "About this experiment"
Let us combine the "About this experiment" notes across the 4 tabs for gRPC and 2 tabs for HTTP.

2023-02-14 16:23 UTC, sriumcp commented on docs/tutorials/load-test-grpc.md
> +    kubectl create deployment routeguide  --image=golang --port=50051 -- bash -c "git clone -b v1.52.0 --depth 1 https://github.com/grpc/grpc-go; cd grpc-go/examples/route_guide; go run server/server
Perhaps `\` new line break before `-- bash`?

2023-02-15 20:54 UTC, sriumcp approved these changes
lgtm

2023-02-15 20:54 UTC, merged