Fix links
iter8-tools/docs pull request #73
Opened 2023-03-21 23:42 UTC by Alan-Cha

The links referring to the documentation of the `http`, `grpc`, and `slack` tasks don't seem to be correct. [See here](https://iter8.tools/0.13/tutorials/autox/autox/#next-steps). This change fixes this issue.

2023-03-23 18:58 UTC, kalantar requested changes

2023-03-23 18:58 UTC, kalantar commented on docs/tutorials/autox/autox.md
> +AutoX is designed to automate a variety of experiments. For example, instead of using the `http` task, you can use `grpc` task in order to run an gRPC SLO validation test. Here is the [documentation]
If the documentation link needs updating, then the tutorial link must as well.

2023-03-23 18:58 UTC, kalantar commented on docs/tutorials/autox/autox.md
> +Furthermore, you can add additional tasks that ship out-of-the-box with Iter8, in order to enrich the experiments. For example, you can add a `slack` task so that your experiment results will be post
same comment

2023-03-23 20:46 UTC, Alan-Cha commented
I found a few more broken links. Seems like we should definitely have some kind of link checker workflow.

2023-03-24 15:04 UTC, Alan-Cha commented
See #76

2023-03-24 19:12 UTC, closed without merging